apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nodered
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{image}}
  port: 1880
  liveness:
    path: /
    initialDelay: 20
  readiness:
    path: /
    initialDelay: 20
  resources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 32Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  ingresses:
    - "https://nodered.ansatt.nav.no"