apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  name: nodered
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{image}}
  port: 1880
  accessPolicy:
  outbound:
    external:
      - host: bigquery.googleapis.com
        ports:
          - port: 443
      - host: oauth2.googleapis.com
        ports:
          - port: 443
      - host: accounts.google.com
        ports:
          - port: 443
      - ipv4: 74.125.131.84
      - ipv4: 74.125.0.0/16
      - ipv4: 108.177.0.0/16
      - ipv4: 172.217.0.0/16
      - ipv4: 142.250.0.0/15
      - ipv4: 108.177.14.84
      - ipv4: 173.194.221.84
      - ipv4: 64.233.164.84
  liveness:
    path: /
    initialDelay: 20
    port: 1880
  readiness:
    path: /
    initialDelay: 20
    port: 1880
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  ingresses:
    - "https://nodered.ansatt.nav.no"